{
 "title": "New dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "KPI - Ticket Médio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG((preco_unitario / 100.0) * quantidade) AS \"Ticket Médio\"\nFROM\n  vendas\nWHERE\n  $__timeFilter(data_venda);"
    }
   ]
  },
  {
   "title": "Análise de Receita",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', data_venda) AS time,\n  SUM((preco_unitario / 100.0) * quantidade) AS \"Receita\"\nFROM\n  vendas\nWHERE\n  $__timeFilter(data_venda)\nGROUP BY\n  time\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Desempenho Relativo das Categorias",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT\n  categoria,\n  SUM((preco_unitario / 100.0) * quantidade) AS \"total_receita\"\nFROM\n  vendas\nWHERE\n  $__timeFilter(data_venda)\nGROUP BY\n  categoria\nORDER BY\n  \"total_receita\" DESC;"
    }
   ]
  }
 ]
}